# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0beb390334846b52aaf2c3fdde5ea62e22a38eb6d1f59d0a2f5feb3bc0ec7a52f9973777d027e652d6decc106f45079d71a0e9736663f5ffde6e016967ce19e6

test:
  secret_key_base: 1c614fabbadf7fccdb2200ba7b72df418d85e2489cd21a2c19e502cdc389c9232d7590fbc5acdcf0c5371aa409f200534c1b7d7183682dc35cf5c9474db2a147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
